# Generated by Django 4.0.6 on 2022-07-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
