# Generated by Django 4.0.6 on 2022-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_person_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
