# Generated by Django 4.0.6 on 2022-07-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_cars_delete_car_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
