# Generated by Django 4.0.6 on 2022-07-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='student_name',
        ),
    ]
