# Generated by Django 4.0.6 on 2022-07-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_users_alter_account_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
