# Generated by Django 4.0.6 on 2022-07-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
